### ISSUE TITLE
 Misundersatnding of customTools seetings

### ISSUE THREAD

**Issue by MHDINGBI** [davidvadkerti/customtools#1]
Hi Mister David, 
I was Trying to use you customTools Dashboard.
But i don't really understand how to make the seetings.
If you can make a vidéo showing how to do it in a simple way.
Note that we're not familiar with the world of programming.
Thanks

**Comment by davidvadkerti** [comment]
Hi,
this is just the forked od the project. You can find up to date CustomTools git repo at bitbucket - https://bitbucket.org/davidvadkerti/customtools/src/master/

I will definitely create a video showing how you can set up your working dashboards using my templates.
thanks for the feedback :)
